# Exercise configuration file

agent_base: "duckietown_ml"
ws_dir: "solution" # directory that contains the code the user needs to see
lab_dir: .         # directory to be mounted into the jupyter container
agent_run_cmd: "run_pedestrian.sh" # the script in "launchers" to run the agent with
ros: true
challenge: mooc-objdet
rsync_exclude:
  - "solution/duckietown_dataset"